title: "Hugo Viala"
description: "This is a blog about me filling my computer's memory."
about: "This is a blog about me filling my computer's memory."
location: "Paris, France"
email: hugo.viala@gmail.com
baseurl: ""
url: "http://rivten.github.io" # replace by your site's url
twitter_username: hugoviala
github_username:  rivten

# google analytics tracking code, please change the value
#g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "About"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
